_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 55
                - 95
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 55
                - 95
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
epochs:
    value: 1
k:
    value: 4
lr:
    value: 1e-06
max_length:
    value: 512
max_lr:
    value: 1e-06
